/// Keywords of `first-step`.
#[derive(Clone, Debug, PartialEq)]
pub enum Keyword {
  If, Else, Return,
}

/// Operators of `first-step`.
#[derive(Clone, Debug, PartialEq)]
pub enum Operator {
  Add, Sub, Mul, Div, Mod,
  Less, LessEq, Eq, NotEq,
  LAnd, LOr, LNot,
  Define, Assign,
}

/// Token generated by `Lexer`.
#[derive(Debug, PartialEq)]
pub enum Token {
  /// End of file
  End,
  /// Identifier
  Id(String),
  /// Integer literal
  Int(i32),
  /// Keyword
  Key(Keyword),
  /// Operator
  Op(Operator),
  /// Other characters
  Other(char),
}
