use std::string::String;

// Keywords of first-step.
pub enum Keyword {
  If, Else, Return,
}

// Operators of first-step.
pub enum Operator {
  Add, Sub, Mul, Div, Mod,
  Less, LessEq, Eq, NotEq,
  LAnd, LOr, LNot,
  Define, Assign,
}

// Token generated by Lexer.
pub enum Token {
  // error
  Error,
  // end
  End,
  // identifier
  Id(String),
  // integer literal
  Int(i32),
  // keyword
  Key(Keyword),
  // operator
  Op(Operator),
  // other character
  Other(char),
}
